# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
#
# Bitwarden Machine Account Access Token
#
# IMPORTANT: This file must be encrypted with SOPS before committing!
#
# To create this secret:
# 1. Go to Bitwarden > Secrets Manager > Machine Accounts
# 2. Create a new Machine Account or use an existing one
# 3. Generate an Access Token with Read-Write permissions to your project
# 4. Replace the placeholder token below with your actual token
# 5. Encrypt with SOPS: sops -e -i secret.sops.yaml
#
# The token format is a long base64-encoded string starting with "0."
#
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ThmCKBYuI2o+vsO5jzczWkH3UlDqIPD4IjydYfNqYkNfUpo+LCbqwa3MEAV5I15VWqBybYWRJvN4KFscpB7bQbVLPzZC8FLem18=,iv:3wCtRuMGc+7WKqPG5JBJQWlrKaGfYndori4MCAT/eKs=,tag:RuIffArGNSQU104tbgZfBQ==,type:comment]
  #ENC[AES256_GCM,data:KGcuG/Y9g4QXvGr4bOhAq1svXRT+yUwpUK6UAT+Fw3cEbjpGzKpl02k=,iv:ocTTVHpXMN66dH6CyjMQlruVtqTY5B5++1XYB68nt9o=,tag:hQXcmu4jkNNWywrjjuxEfg==,type:comment]
  token: ENC[AES256_GCM,data:QttcArWx9YIi/9GQsM8CX7HFrn+pxfD7mehF/dhkspgySJNH42/c/Oa9tkHh84AAo8AtH/iYBe+MjD5xUQUaWnjRCLDCuhvFgJWeCH3G22jtm7aTKOyLUKxrZr1+Yg==,iv:iyKfSQ0WnHOC/ZHTSyq+PYS6f8w0/AQEzO+oo485+5Q=,tag:pGDORo549gGkOjp6DiW5jw==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL2FJODkrVzdRTEozVFFM
        TVk1b3FJYlVKSFZmVHJ0OTI4UmFrZWpPNHpZCkVldXJHMDgxcmNkeHVvQXBsYTE0
        YnBmcVVDSE1sNWZjQjhZSzNkYzEzbWcKLS0tIENxUzVOaFAzbVFuKzVheDVwUDBJ
        MkpCRFpqeFJ2K2lqNDlQYU10NmVoMUEKBozp0wn/ywbvzq/+J7Zi++QJn4vk30BX
        V+u0Hf7cdbm+bnl3qB7EYrA5x4d5Xr4EOTmAcV9hRJ6evb1JWaxwNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T21:37:17Z"
  mac: ENC[AES256_GCM,data:xysCa06Zyyr5K4RootDkmisjpKjhlqWOBYGZrbWzETqWCCIFUh/Ykg7OmskYD056P6XzGL2dWuQZ8m2nr3sS7gGeTk+vijBDuBRNhxLCR0Y6GddtQXjbq5KvUCNBD5L5DNxQAFb+76vrQB/Sed40xTP+j332hY2zd2p20H1dQbE=,iv:1OReppXrQ6w7O/t/Nygi18mMMWZxUxnzem13QYqMNNs=,tag:dUmNB12FBo4tUV1aPqcqzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
