---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  # Backup schedules for applications
  - ./schedules/pricebuddy-schedule.yaml
  - ./schedules/n8n-schedule.yaml
  - ./schedules/immich-schedule.yaml
  - ./schedules/gatus-schedule.yaml
  - ./schedules/obsidian-livesync-schedule.yaml
  - ./schedules/pocket-id-schedule.yaml
  - ./schedules/matrix-schedule.yaml
