---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./externalsecret-grafana-oauth.yaml
  - ./prometheusrule-apps.yaml
  - ./prometheusrule-storage.yaml
  - ./prometheusrule-gameserver.yaml
  - ./grafana-dashboard-gameserver.yaml
  - ./grafana-dashboard-cluster.yaml
