# IMPORTANT: This file must be encrypted with SOPS before committing
# Run: sops -e -i secret.sops.yaml
#
# This secret contains the Bitwarden Secrets Manager access token
# Generate this token from: Bitwarden Web Vault > Secrets Manager > Machine Accounts
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
type: Opaque
stringData:
  #ENC[AES256_GCM,data:GoqKs/58Qt/dchezaIPDq/jjEjKU7WwnK1r92oZk2dzaIXgJrAlFG5uyKIpepZbVnhibDMrnAf8ga//bj15IUQ==,iv:CO6ymbLflnefVVfz6gyYXAaey8D8X/q7138Cx8TdGPg=,tag:Nx7/ryim3wWheZM090izlg==,type:comment]
  token: ENC[AES256_GCM,data:AryKXhgzIWSLxqTaPiGjvElVYW9RpNndIly4zRG84FfwtMtQESzKYMhX13CX3EhVoW9ANzxZI9zSYPbkP21xB2oScj9reu+FGWK/TiR3c+gSvOppfLkijbIVvPxT3g==,iv:H/CSYO0ROwzb69XXKK9v7zdJV7oTm1acMc8+gr4k6rQ=,tag:IfBRfR71qFpY4L7SklXCHw==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZkRuZVNwdlozTHJZWG5Q
        NURVQU9rSVk4ZGdnZkRmMG9za3cySGM3UjBBCjNIMHhwV0ZiQ1VueStwWmcwUkhY
        RS9wN3F2b0UrSVZxNlU3ODNWYjFKRzAKLS0tIFlyWnE4eHRnNlU4dkZjWE5SOXI1
        WW93cWgwVUxuWFVudllxOFJ2M3JKaGMKTcp4rX+tEx47SSlzjODK/MAICdGyA5hC
        g7hY6gnrJZ8UiOAtUjdsQCDu6ouwYcl84DfTlMZQjmVV7bqBzOqL3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T16:33:55Z"
  mac: ENC[AES256_GCM,data:vdOCf1DyZ1gnGsx+SIjvyqT3zGWlQnaQAD915YN0ZmyDkEdUg4DVAh2gwjzigOiLOLsiFCPi59a9L+DnAfNjFlpy1/B2sWafabdVOTCEe9HM7ntnceZoYEBQRELvUSQ/l+hxHQODr8hV5YpPtCFM423rMIz8QptX57OLSatPCxs=,iv:8YUG3BP/iEimXjrezbWRMdLSvca28S6Ht88KwJBt1jg=,tag:6XZCEtdRXH1L9xoQHgFdpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
