# https://artifacthub.io/packages/helm/open-webui/open-webui?modal=values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
spec:
  interval: 1h
  chart:
    spec:
      chart: firefly-iii-stack
      # version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: firefly
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    firefly-db:
      # if you set this to false it will not be installed
      enabled: true
      image:
        repository: postgres
        tag: 18-alpine
        pullPolicy: IfNotPresent

      storage:
        class: longhorn
        # accessModes: ~  # Change as needed for your storageClass https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
        dataSize: 1Gi

      # environment variables
      configs:
        RESTORE_URL: ""
        BACKUP_URL: ""
        PGPASSWORD: ""
        DBHOST: ""  # Default is the name of the postgres service
        DBPORT: "5432"
        DBNAME: firefly
        DBUSER: firefly
        TZ: "America/New_York"

      backupSchedule: "0 3 * * *"

    firefly-iii:
      # -- Set to false to not deploy Firefly III
      enabled: true
      config:
        env:
          DB_HOST: ""
          DEFAULT_LANGUAGE: "en_US"
          DEFAULT_LOCALE: "equal"
          TZ: "America/New_York"
          TRUSTED_PROXIES: "**"

    importer:
      # -- Set to false to not deploy the importer
      enabled: true