---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/instance: pocket-id
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: pocket-id
spec:
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  hostnames: ["auth.endsys.cloud"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pocket-id
          port: 80
