---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: gatus
      version: 1.4.4
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    persistance:
      enabled: true
      size: 20Gi
    config:
      metrics: true
      ui:
        title: Status | Gatus
        header: Status
        logo: https://avatars.githubusercontent.com/u/7853316
        link: https://github.com/shelmus
        buttons:
          - name: Github
            link: https://github.com/shelmus
          - name: Homelab
            link: https://github.com/shelmus/endsys-gitops
      endpoints:
        - name: echo-server
          enabled: true
          group: external
          url: https://echo.endsys.cloud
          interval: 1m
          client:
            dns-resolver: tcp://1.1.1.1:53
          conditions:
            - '[STATUS] == 200'
        - name: flux-webhook
          enabled: true
          group: external
          url: https://flux-webhook.endsys.cloud
          interval: 1m
          client:
            dns-resolver: tcp://1.1.1.1:53
          conditions:
            - "[STATUS] == 404"
        - name: minecraft-vanilla
          enabled: true
          group: external
          url: tcp://games.endsys.cloud:25567
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: minecraft-creative
          enabled: true
          group: external
          url: tcp://games.endsys.cloud:25565
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: vaulthunters
          enabled: true
          group: external
          url: tcp://games.endsys.cloud:25566
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: vaulthunters sky
          enabled: true
          group: external
          url: tcp://games.endsys.cloud:25570
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: TerraFermaGreg
          enabled: true
          group: external
          url: tcp://games.endsys.cloud:25569
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: kube1
          enabled: true
          group: internal
          url: tcp://10.127.0.41:50000
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: kube2
          enabled: true
          group: internal
          url: tcp://10.127.0.42:50000
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
        - name: kube3
          enabled: true
          group: internal
          url: tcp://10.127.0.43:50000
          interval: 1m
          conditions:
            - "[CONNECTED] == true"