---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-secrets
  labels:
    app.kubernetes.io/name: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: matrix-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        mas-db-password: "{{ .masDbPassword }}"
        MATRIX_OAUTH_CLIENT_SECRET: "{{ .oauthClientSecret }}"
        MATRIX_OAUTH_CLIENT_ID: "{{ .oauthClientId }}"
        postgres-init-sql: |
          CREATE USER mas WITH PASSWORD '{{ .masDbPassword }}';
          CREATE DATABASE matrix_authentication_service OWNER mas;
  data:
    - secretKey: masDbPassword
      remoteRef:
        key: matrix-mas-db-password
    - secretKey: oauthClientSecret
      remoteRef:
        key: matrix-oauth-client-secret
    - secretKey: oauthClientId
      remoteRef:
        key: matrix-oauth-client-id
