---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-synapse-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
  storage:
    size: 10Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-mas-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: matrix_authentication_service
      owner: mas
  storage:
    size: 5Gi
