---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
      postInitApplicationSQLRefs:
        secretRefs:
          - name: matrix-secrets
            key: postgres-init-sql
  storage:
    size: 10Gi
