---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
spec:
  interval: 30m
  chart:
    spec:
      chart: seaweedfs
      version: 4.0.400
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    s3:
      enabled: true
      accessKeyFromSecret:
        name: velero-s3-credentials
        key: accessKey
      secretKeyFromSecret:
        name: velero-s3-credentials
        key: secretKey
    master:
      persistence:
        existingClaim: "seaweedfs-nfs-pvc"
        subPath: "master"
    volume:
      persistence:
        existingClaim: "seaweedfs-nfs-pvc"
        subPath: "volume"