---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-dns.yaml
  - ./bitwarden.yaml
  - ./rook-ceph.yaml
  - ./piraeus.yaml
  - ./kube-prometheus-stack.yaml
  - ./n8n.yaml
  - ./otterwiki.yaml
  - ./twin.yaml
  - ./longhorn.yaml
  - ./backube.yaml
  - ./csi-driver-nfs.yaml
  - ./vmware-tanzu.yaml
  - ./rocm-k8s-plugin.yaml
  - ./rocm-operator.yaml
  - ./seaweedfs.yaml
  - ./immich.yaml
  - ./external-secrets.yaml
  - ./anza-labs.yaml
  - ./cnpg.yaml
  - ./dragonfly.yaml