---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pricebuddy
  labels:
    app.kubernetes.io/name: pricebuddy
spec:
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  hostnames: ["pricebuddy.endsys.cloud"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pricebuddy
          port: 80
