---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./database-deployment.yaml
  - ./scraper-deployment.yaml
  - ./service.yaml
  - ./pvc.yaml
  - ./httproute.yaml
  - ./secret.sops.yaml
