---
apiVersion: v1
kind: Service
metadata:
  name: pricebuddy
  labels:
    app.kubernetes.io/name: pricebuddy
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: pricebuddy
    app.kubernetes.io/component: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: pricebuddy-database
  labels:
    app.kubernetes.io/name: pricebuddy
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: pricebuddy
    app.kubernetes.io/component: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: pricebuddy-scraper
  labels:
    app.kubernetes.io/name: pricebuddy
    app.kubernetes.io/component: scraper
spec:
  selector:
    app.kubernetes.io/name: pricebuddy
    app.kubernetes.io/component: scraper
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
