---
apiVersion: v1
kind: Endpoints
metadata:
  name: gameserver
subsets:
  - addresses:
      - ip: 10.127.0.7
    ports:
      - name: node-exporter
        port: 9100
      - name: cadvisor
        port: 9080
