---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gameserver
  labels:
    app.kubernetes.io/name: gameserver
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gameserver
  endpoints:
    - port: node-exporter
      path: /metrics
      interval: 30s
    - port: cadvisor
      path: /metrics
      interval: 30s
