---
apiVersion: v1
kind: Service
metadata:
  name: gameserver
spec:
  clusterIP: None
  ports:
    - name: node-exporter
      port: 9100
      targetPort: 9100
    - name: cadvisor
      port: 9080
      targetPort: 9080
