apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:oq4TqNKC391+G/h4,iv:WRHsEBwznGGGvOL9Q40FTImo3vcVPEHv4YHNMWQZmF8=,tag:/oYIaygCtORyhdKP2F6Srw==,type:str]
  SECRET_BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:oGnwsl7a6rWxpqIpxzY0Dqs6BPeblSTb1eiEU8qW0DDYieGR,iv:0WSl30xE8NyLmuc7AoyY8r64iOhUIxv0is9sbhYzUTo=,tag:w+bA8eCfYMzfE3TNlID6dQ==,type:str]
  SECRET_BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:SsDMgyhB795pR8hJkzgsGWcOq2Ic9T5hWfAct8OG7sW0H/6K,iv:+csxlDsMIBZof268ck7q77ALYYHG5CKvRsTpLQyZWag=,tag:oj5A0uPT2wU2QeOisPIdDA==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMHBoUFRTMVk4ZmpXbVVR
        SFhmaExWcStQejlpVWVIcm16Q3p3NVd4VHpFCmpXSW10NTA0YktrTzN5R01GUm45
        OVpLNGYzSzdsZjYrRE92L0JVeUNSRUkKLS0tIFFQZ0NzalAyZDVMcXlDdGhPWWND
        MnNpTmVsb0REaEY4RTM5Y1FDSFkyTk0KqRVN5zHY4rE4ZbhNZYbKatIHPk1yOvAJ
        WrxiCt/78hZp5biPix7h2N6MBlRwWJA0SKA9Hp8OWWgKi8eFc7jXzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T22:05:55Z"
  mac: ENC[AES256_GCM,data:cJXZnWXyyTrzFSEmn5K+xXwy7ThnoGjjUxNL19MeiQ0oN8+EJYiTCMFGLPG2nqU+i7+zP3iAmy9vjEGAKMGesrkfusdR4wlDNLaPOSKo8nDI6BaUMNwNGvljur71ekwn6AyytwKhmHaB7bZzQyqx0pkBakHMZz1VyVIWyMNPHfk=,iv:wZrZavxf7N7MFE+sHnpZiMmpG56lbl2D6L9YNGjOQbI=,tag:WbyoiLEANuozJrlK/wDLdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
